version = 1
tools = [
    "codex",
    "pi",
]

[installed_skills.consult-advisor]
added = "2026-08-02"
source = "https://github.com/ydeng11/agentskills/tree/main/skills/consult-advisor"
commit_sha = "841513ce97742f2436e88ba90dcec4f41d16bb2f"
scope = "project"
covered_tools = ["pi"]

[installed_skills.handoff]
added = "2026-06-26"
source = "https://github.com/mattpocock/skills/tree/main/skills/productivity/handoff"
commit_sha = "d54c497aa94400a496d3f2c38be10fa5f284c5a9"
scope = "project"
covered_tools = ["pi"]

[installed_skills.stop-slop]
added = "2026-08-12"
source = "https://github.com/hardikpandya/stop-slop/tree/main"
commit_sha = "8da1f030185bdfe8471220585162991eaeb970e9"
scope = "project"
covered_tools = ["pi"]

[installed_skills.review]
added = "2026-07-13"
source = "https://github.com/mattpocock/skills/tree/main/skills/in-progress/review"
commit_sha = "9fecab929abb904c68ce3366a1781df31ab22832"
scope = "project"
covered_tools = ["pi"]
