import { afterEach, describe, expect, it } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import {
  generateMediaCorpus,
  GENERATED_MEDIA_CORPUS_FILES,
  MEDIA_CORPUS_FILES,
} from "../helpers/media-corpus";
import { readTrackMetadata } from "../../electron/handlers/tracks";

const fixtureRoot = path.resolve(
  process.cwd(),
  "test/fixtures/tauri/media-corpus",
);
const expectedPath = path.join(fixtureRoot, "expected.json");
const generatedRoots: string[] = [];

function temporaryRoot(): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "auto-tagger-media-corpus-"));
  generatedRoots.push(root);
  return root;
}

async function normalizedElectronBaseline(root: string) {
  const tracks = await Promise.all(
    MEDIA_CORPUS_FILES.map(async (file) => {
      const track = await readTrackMetadata(path.join(root, file));
      // Canonical DesktopAPI declares lyrics as string|null. music-metadata's
      // ID3 path currently leaks an object through Electron's unsafe cast; the
      // normalized cross-runtime fixture intentionally extracts `.text` while
      // a separate characterization below preserves evidence of the raw defect.
      const rawLyrics = track.lyrics as unknown;
      const lyrics =
        typeof rawLyrics === "string"
          ? rawLyrics
          : rawLyrics &&
              typeof rawLyrics === "object" &&
              "text" in rawLyrics &&
              typeof (rawLyrics as { text?: unknown }).text === "string"
            ? (rawLyrics as { text: string }).text
            : null;
      return { ...track, path: file, lyrics };
    }),
  );
  // JSON normalization intentionally removes undefined/non-finite JS-only
  // values, so Rust consumes the canonical renderer DTO shape.
  return JSON.parse(JSON.stringify(tracks));
}

async function regenerateWhenExplicitlyRequested(generatedRoot: string) {
  if (process.env.UPDATE_MEDIA_CORPUS !== "1") return;
  // Preserve real-encoder fixtures; only replace files generated by the TS
  // helpers. FFmpeg fixtures have their own explicit script/provenance.
  fs.mkdirSync(fixtureRoot, { recursive: true });
  for (const file of GENERATED_MEDIA_CORPUS_FILES) {
    fs.copyFileSync(path.join(generatedRoot, file), path.join(fixtureRoot, file));
  }
  fs.writeFileSync(
    expectedPath,
    JSON.stringify(await normalizedElectronBaseline(fixtureRoot), null, 2) + "\n",
  );
}

afterEach(() => {
  for (const root of generatedRoots.splice(0)) {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

describe("shared Electron/Rust media corpus", () => {
  /**
   * Intent: Rust must consume the exact bytes synthesized by the established
   * Electron helpers, not independently recreated “equivalent” media. Updating
   * artifacts requires an explicit env flag and also refreshes expected.json.
   */
  it("committed corpus bytes are generated by the extracted Electron helpers", async () => {
    const generatedRoot = temporaryRoot();
    await generateMediaCorpus(generatedRoot);
    await regenerateWhenExplicitlyRequested(generatedRoot);

    for (const file of GENERATED_MEDIA_CORPUS_FILES) {
      expect(fs.readFileSync(path.join(fixtureRoot, file))).toEqual(
        fs.readFileSync(path.join(generatedRoot, file)),
      );
    }
  });

  /**
   * Intent: expected.json is the Electron read-path baseline for every normal,
   * malformed-FLAC, and APE+ID3v1 fallback file. The future Lofty reader must
   * match this normalized renderer payload before writer work begins.
   */
  it("committed normalized metadata baseline matches Electron readTrackMetadata", async () => {
    const expected = JSON.parse(fs.readFileSync(expectedPath, "utf-8"));
    expect(await normalizedElectronBaseline(fixtureRoot)).toEqual(expected);
  });

  /**
   * Pre-existing Electron contract defect: desktop-api.ts declares lyrics as
   * string|null, but ID3 music-metadata emits an object and tracks.ts currently
   * leaks it through an unsafe cast. Renderer consumers guard typeof string and
   * therefore ignore this object. Tauri keeps the canonical string contract;
   * normalizedElectronBaseline extracts `.text` explicitly.
   */
  it("characterizes raw Electron ID3 lyrics object leakage", async () => {
    const raw = await readTrackMetadata(path.join(fixtureRoot, "minimal.mp3"));
    expect(raw.lyrics as unknown).toEqual({
      language: "eng",
      descriptor: "",
      text: "Corpus Lyrics",
    });
  });

  /**
   * Pre-existing Electron writer/read characterization: the production writer
   * persists COMPILATION=true in a TXXX row, but music-metadata's `common`
   * normalization does not populate common.compilation, so TrackData is null.
   * Preserve evidence; do not silently "fix" it in the migration reader.
   */
  it("characterizes production MP3 compilation readback as null", async () => {
    const raw = await readTrackMetadata(path.join(fixtureRoot, "minimal.mp3"));
    expect(raw.compilation).toBeNull();
  });
});
