import { afterEach, describe, expect, it } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import {
  generateMediaCorpus,
  MEDIA_CORPUS_FILES,
} from "../helpers/media-corpus";
import { readTrackMetadata } from "../../electron/handlers/tracks";

const fixtureRoot = path.resolve(
  process.cwd(),
  "test/fixtures/tauri/media-corpus",
);
const expectedPath = path.join(fixtureRoot, "expected.json");
const generatedRoots: string[] = [];

function temporaryRoot(): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "auto-tagger-media-corpus-"));
  generatedRoots.push(root);
  return root;
}

async function normalizedElectronBaseline(root: string) {
  const tracks = await Promise.all(
    MEDIA_CORPUS_FILES.map(async (file) => ({
      ...(await readTrackMetadata(path.join(root, file))),
      path: file,
    })),
  );
  // JSON normalization intentionally removes any undefined JS-only values, so
  // Rust consumes the exact committed renderer payload shape.
  return JSON.parse(JSON.stringify(tracks));
}

async function regenerateWhenExplicitlyRequested(generatedRoot: string) {
  if (process.env.UPDATE_MEDIA_CORPUS !== "1") return;
  fs.rmSync(fixtureRoot, { recursive: true, force: true });
  fs.mkdirSync(fixtureRoot, { recursive: true });
  for (const file of MEDIA_CORPUS_FILES) {
    fs.copyFileSync(path.join(generatedRoot, file), path.join(fixtureRoot, file));
  }
  fs.writeFileSync(
    expectedPath,
    JSON.stringify(await normalizedElectronBaseline(fixtureRoot), null, 2) + "\n",
  );
}

afterEach(() => {
  for (const root of generatedRoots.splice(0)) {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

describe("shared Electron/Rust media corpus", () => {
  /**
   * Intent: Rust must consume the exact bytes synthesized by the established
   * Electron helpers, not independently recreated “equivalent” media. Updating
   * artifacts requires an explicit env flag and also refreshes expected.json.
   */
  it("committed corpus bytes are generated by the extracted Electron helpers", async () => {
    const generatedRoot = temporaryRoot();
    await generateMediaCorpus(generatedRoot);
    await regenerateWhenExplicitlyRequested(generatedRoot);

    for (const file of MEDIA_CORPUS_FILES) {
      expect(fs.readFileSync(path.join(fixtureRoot, file))).toEqual(
        fs.readFileSync(path.join(generatedRoot, file)),
      );
    }
  });

  /**
   * Intent: expected.json is the Electron read-path baseline for every normal,
   * malformed-FLAC, and APE+ID3v1 fallback file. The future Lofty reader must
   * match this normalized renderer payload before writer work begins.
   */
  it("committed normalized metadata baseline matches Electron readTrackMetadata", async () => {
    const expected = JSON.parse(fs.readFileSync(expectedPath, "utf-8"));
    expect(await normalizedElectronBaseline(fixtureRoot)).toEqual(expected);
  });
});
